//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Store_Project.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ProductsInOrder = new HashSet<ProductsInOrder>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int PickUpPointID { get; set; }
        public int PickUpCode { get; set; }
        public int StatusOrderID { get; set; }
    
        public virtual PickUpPoints PickUpPoints { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInOrder> ProductsInOrder { get; set; }
    }
}
